# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datapane.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="datapane.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0e\x64\x61tapane.proto"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t"\x1f\n\x05\x45mpty\x12\x16\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x06.Error"1\n\x04Pong\x12\x16\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x06.Error\x12\x11\n\ttimestamp\x18\x02 \x01(\x01"+\n\x11\x43\x61lculationInputs\x12\t\n\x01x\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x94\x01\n\x04Main\x12\x17\n\x05Start\x12\x06.Empty\x1a\x06.Empty\x12\x16\n\x04Stop\x12\x06.Empty\x1a\x06.Empty\x12\x1b\n\tTerminate\x12\x06.Empty\x1a\x06.Empty\x12\x15\n\x04Ping\x12\x06.Empty\x1a\x05.Pong\x12\'\n\tCalculate\x12\x12.CalculationInputs\x1a\x06.Emptyb\x06proto3',
)


_ERROR = _descriptor.Descriptor(
    name="Error",
    full_name="Error",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="Error.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=18,
    serialized_end=42,
)


_EMPTY = _descriptor.Descriptor(
    name="Empty",
    full_name="Empty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="errors",
            full_name="Empty.errors",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=75,
)


_PONG = _descriptor.Descriptor(
    name="Pong",
    full_name="Pong",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="errors",
            full_name="Pong.errors",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="Pong.timestamp",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=77,
    serialized_end=126,
)


_CALCULATIONINPUTS = _descriptor.Descriptor(
    name="CalculationInputs",
    full_name="CalculationInputs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="x",
            full_name="CalculationInputs.x",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="msg",
            full_name="CalculationInputs.msg",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=128,
    serialized_end=171,
)

_EMPTY.fields_by_name["errors"].message_type = _ERROR
_PONG.fields_by_name["errors"].message_type = _ERROR
DESCRIPTOR.message_types_by_name["Error"] = _ERROR
DESCRIPTOR.message_types_by_name["Empty"] = _EMPTY
DESCRIPTOR.message_types_by_name["Pong"] = _PONG
DESCRIPTOR.message_types_by_name["CalculationInputs"] = _CALCULATIONINPUTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType(
    "Error",
    (_message.Message,),
    {
        "DESCRIPTOR": _ERROR,
        "__module__": "datapane_pb2"
        # @@protoc_insertion_point(class_scope:Error)
    },
)
_sym_db.RegisterMessage(Error)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "datapane_pb2"
        # @@protoc_insertion_point(class_scope:Empty)
    },
)
_sym_db.RegisterMessage(Empty)

Pong = _reflection.GeneratedProtocolMessageType(
    "Pong",
    (_message.Message,),
    {
        "DESCRIPTOR": _PONG,
        "__module__": "datapane_pb2"
        # @@protoc_insertion_point(class_scope:Pong)
    },
)
_sym_db.RegisterMessage(Pong)

CalculationInputs = _reflection.GeneratedProtocolMessageType(
    "CalculationInputs",
    (_message.Message,),
    {
        "DESCRIPTOR": _CALCULATIONINPUTS,
        "__module__": "datapane_pb2"
        # @@protoc_insertion_point(class_scope:CalculationInputs)
    },
)
_sym_db.RegisterMessage(CalculationInputs)


_MAIN = _descriptor.ServiceDescriptor(
    name="Main",
    full_name="Main",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=174,
    serialized_end=322,
    methods=[
        _descriptor.MethodDescriptor(
            name="Start",
            full_name="Main.Start",
            index=0,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Stop",
            full_name="Main.Stop",
            index=1,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Terminate",
            full_name="Main.Terminate",
            index=2,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Ping",
            full_name="Main.Ping",
            index=3,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_PONG,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Calculate",
            full_name="Main.Calculate",
            index=4,
            containing_service=None,
            input_type=_CALCULATIONINPUTS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_MAIN)

DESCRIPTOR.services_by_name["Main"] = _MAIN

# @@protoc_insertion_point(module_scope)
